version: 2
updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[TSPS-793]"
    groups:
      gradle-major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
      gradle-other-updates:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "com.fasterxml.jackson.core:*"
        versions: [ "> 2.17.3" ] # Keeps swagger-generator safe
      - dependency-name: "org.apache.commons:commons-lang3"
        versions: [ "> 3.20.0" ] # Preserves Jib vs SourceClear balance

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "[TSPS-793]"
