version: 1.2
workflows:

  - subclass: WDL
    name: CompareVcfs
    primaryDescriptorPath: /pipelines/imputation/testing/CompareVcfs.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: ImputationBeagleEmpty
    primaryDescriptorPath: /pipelines/imputation/testing/ImputationBeagleEmpty.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: QuotaConsumedEmpty
    primaryDescriptorPath: /pipelines/imputation/testing/QuotaConsumedEmpty.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: StdPopSim
    primaryDescriptorPath: /pipelines/imputation/simulatedData/StdPopSim.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: DuplicateVcfAndMerge
    primaryDescriptorPath: /pipelines/imputation/simulatedData/DuplicateVcfAndMerge.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: CreateImputationRefPanelBeagle
    primaryDescriptorPath: /pipelines/imputation/simulatedData/CreateImputationRefPanelBeagle.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: ReshapeReferencePanel
    primaryDescriptorPath: /pipelines/imputation/scientificValidation/ReshapeReferencePanel.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: ReshapeReferencePanelSplitVcf
    primaryDescriptorPath: /pipelines/imputation/scientificValidation/ReshapeReferencePanelSplitVcf.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: SubsetVcfByBedFile
    primaryDescriptorPath: /pipelines/imputation/scientificValidation/SubsetVcfByBedFile.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: UpdateVcfDictionaryHeader
    primaryDescriptorPath: /pipelines/imputation/scientificValidation/UpdateVcfDictionaryHeader.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: BeagleImputationValidation
    primaryDescriptorPath: /pipelines/imputation/scientificValidation/BeagleImputationValidation.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org
