version: 1.2
workflows:

  - subclass: WDL
    name: CompareBcfs
    primaryDescriptorPath: /pipelines/sv_imputation/testing/CompareBcfs.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: CompareVcfs
    primaryDescriptorPath: /pipelines/array_imputation/testing/CompareVcfs.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: CopyReferenceFilesToSameGcsDirectory
    primaryDescriptorPath: /pipelines/low_pass_imputation/refPanelCreation/CopyReferenceFilesToSameGcsDirectory.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: FixSitesVcf
    primaryDescriptorPath: /pipelines/low_pass_imputation/refPanelCreation/FixSitesVcf.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: Glimpse2LowPassImputationEmpty
    primaryDescriptorPath: /pipelines/low_pass_imputation/testing/Glimpse2LowPassImputationEmpty.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: Glimpse2LowPassImputationInputQCEmpty
    primaryDescriptorPath: /pipelines/low_pass_imputation/testing/Glimpse2LowPassImputationInputQCEmpty.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: Glimpse2LowPassImputationQuotaConsumedEmpty
    primaryDescriptorPath: /pipelines/low_pass_imputation/testing/Glimpse2LowPassImputationQuotaConsumedEmpty.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: Glimpse2SplitReference
    primaryDescriptorPath: /pipelines/low_pass_imputation/refPanelCreation/Glimpse2SplitReference.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: ImputationBeagleEmpty
    primaryDescriptorPath: /pipelines/array_imputation/testing/ImputationBeagleEmpty.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: InputQCEmpty
    primaryDescriptorPath: /pipelines/array_imputation/testing/InputQCEmpty.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: LeftAlignVcf
    primaryDescriptorPath: /pipelines/array_imputation/refPanelCreation/LeftAlignVcf.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: LiftoverVcfs
    primaryDescriptorPath: /pipelines/array_imputation/scientificValidation/LiftoverVcfs.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: SplitMultiallelics
    primaryDescriptorPath: /pipelines/array_imputation/refPanelCreation/SplitMultiallelics.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: QuotaConsumedEmpty
    primaryDescriptorPath: /pipelines/array_imputation/testing/QuotaConsumedEmpty.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: RecombineVariantAndHomRefVcfs
    primaryDescriptorPath: /pipelines/array_imputation/scientificValidation/RecombineVariantAndHomRefVcfs.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: StdPopSim
    primaryDescriptorPath: /pipelines/array_imputation/simulatedData/StdPopSim.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: DuplicateVcfAndMerge
    primaryDescriptorPath: /pipelines/array_imputation/simulatedData/DuplicateVcfAndMerge.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: CreateImputationRefPanelBeagle
    primaryDescriptorPath: /pipelines/array_imputation/refPanelCreation/CreateImputationRefPanelBeagle.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: ReshapeReferencePanel
    primaryDescriptorPath: /pipelines/array_imputation/refPanelCreation/ReshapeReferencePanel.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: ReshapeReferencePanelSVImputation
    primaryDescriptorPath: /pipelines/sv_imputation/refPanelCreation/ReshapeReferencePanel.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: SubsetVcfByBedFile
    primaryDescriptorPath: /pipelines/array_imputation/scientificValidation/SubsetVcfByBedFile.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: UpdateVcfDictionaryHeader
    primaryDescriptorPath: /pipelines/array_imputation/scientificValidation/UpdateVcfDictionaryHeader.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: BeagleImputationValidation
    primaryDescriptorPath: /pipelines/array_imputation/scientificValidation/BeagleImputationValidation.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org

  - subclass: WDL
    name: GatkConcordanceValidation
    primaryDescriptorPath: /pipelines/array_imputation/scientificValidation/GatkConcordanceValidation.wdl
    authors:
      - name: Terra Scientific Services
        email: teaspoons-developers@broadinstitute.org
