version: 1.2
workflows:

  - name: CompareVcfs
    subclass: WDL
    primaryDescriptorPath: /pipelines/testing/CompareVcfs.wdl

  - name: ImputationBeagleEmpty
    subclass: WDL
    primaryDescriptorPath: /pipelines/testing/ImputationBeagleEmpty.wdl

  - name: StdPopSim
    subclass: WDL
    primaryDescriptorPath: /pipelines/simulatedData/StdPopSim.wdl
