---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teaspoons
  description: |
    Terra Scientific Pipelines Service, or teaspoons, facilitates running a number of defined scientific pipelines 
    on behalf of users that users can't run themselves in Terra. The most common reason for this is that the pipeline
    accesses proprietary data that users are not allowed to access directly, but that may be used as e.g. a reference panel
    for imputation.
  tags:
    - java
    - dsp
    - terra
    - springboot
  annotations:
    github.com/project-slug: databiosphere/terra-scientific-pipelines-service
  links:
    - url: https://grafana.dsp-devops.broadinstitute.org/d/3VhQ1_0Sz/teaspoons?orgId=1
      title: Teaspoons Grafana Dashboard
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: teaspoons
  system: terra
  dependsOn:
    - component:cbas
    - component:leonardo
    - component:sam
    - component:terra-workspace-manager
    - component:wds
  providesApis:
    - teaspoons-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: teaspoons-api
  description: |
    Placeholder API description...
  tags:
    - java
    - dsp
    - terra
    - springboot
  annotations:
    github.com/project-slug: databiosphere/terra-scientific-pipelines-service
spec:
  type: openapi
  lifecycle: experimental
  system: terra
  owner: teaspoons
  definition:
    $text: ./common/openapi.yml
---
