# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  db:
    host: jdbc:postgresql://${DATABASE_HOSTNAME:127.0.0.1}:5432
    init: ${INIT_DB:false}
    pipelines:
      name: ${DATABASE_NAME:pipelines_db}
      pass: ${DATABASE_USER_PASSWORD:dbpwd}
      user: ${DATABASE_USER:dbuser}
  tracing:
    exportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
  urls:
    sam: ${SAM_ADDRESS:https://sam.jsoto-fourth-try.bee.envs-terra.bio/}
    leonardo: ${LEONARDO_ADDRESS:https://leonardo.jsoto-fourth-try.bee.envs-terra.bio/}
  imputation:
    # default workspace id is for this workspace in the dev environment
    # https://bvdp-saturn-dev.appspot.com/#workspaces/tsps_dev_BP/Imputation_Control_Workspace_test.
    # this should be updated when trying to run on a bee.
    workspaceId: ${IMPUTATION_WORKSPACE_ID:5046acb0-32a1-437d-9a18-fac6897c8f03}

# Below here is non-deployment-specific

# When the target is 'local' the write-config.sh script will generate this properties file. It
# contains the configuration of the TSPS test application. We can use that application in our
# integration testing to make sure the application code paths are working. However, we do not
# want it to appear in production environments.
# Imports are treated as additional documents inserted below this one, so the
# properties in local-properties are guaranteed to override values here in application.yml
spring.config.import: optional:file:../config/local-properties.yml, classpath:rendered/version.properties

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: pipelines

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 8 # cpu count * 2 https://kwahome.medium.com/database-connections-less-is-more-86c406b6fad
    password: ${env.db.pipelines.pass}
    uri: ${env.db.host}/${env.db.pipelines.name}
    url: ${env.db.host}/${env.db.pipelines.name}
    username: ${env.db.pipelines.user}

  liquibase:
    change-log: '/db/changelog.xml'
    contexts: dev # This line currently does nothing but tell it NOT to pick up the test context, which holds test data

  main:
    allow-bean-definition-overriding: true

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
      static-locations: classpath:/static/

terra.common:
  kubernetes:
    in-kubernetes: false

  tracing:
    stackdriverExportEnabled: ${env.tracing.exportEnabled}
    samplingRate: ${env.tracing.samplingRate}

pipelines:
  ingress:
    # Default value that's overridden by Helm.
    domainName: localhost:8080

  status-check:
    enabled: true
    pollingIntervalSeconds: 60
    startupWaitSeconds: 5
    stalenessThresholdSeconds: 125

  sam:
    basePath: ${env.urls.sam}

imputation:
  workspaceId: ${env.imputation.workspaceId}

leonardo:
  baseUri: ${env.urls.leonardo}
  # The below appTypeNames are in priority order for the named app type. This order is necessary for
  # the appComparisonFunction() located in AppUtils.java for selecting the best app for each app type.
  wdsAppTypeNames: ['WDS']
  cbasAppTypeNames: ['CROMWELL']
  dependencyUrlCacheTtlSeconds: 300 # Refresh every 5 minutes
  debugApiLogging: false
