# All env variables that are used in one place
# This is for deployment-specific values, which may be managed by other teams
env:
  db:
    host: jdbc:postgresql://${DATABASE_HOSTNAME:127.0.0.1}:5432
    init: ${INIT_DB:false}
    pipelines:
      name: ${DATABASE_NAME:pipelines_db}
      pass: ${DATABASE_USER_PASSWORD:dbpwd}
      user: ${DATABASE_USER:dbuser}
    stairway:
      name: ${STAIRWAY_DATABASE_NAME:tsps_stairway_db}
      pass: ${STAIRWAY_DATABASE_USER_PASSWORD:stairwaypwd}
      user: ${STAIRWAY_DATABASE_USER:stairwayuser}
  tracing:
    exportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
  urls:
    sam: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org}
    leonardo: ${LEONARDO_ADDRESS:https://leonardo.dsde-dev.broadinstitute.org}
  ingress:
    domainName: ${TSPS_INGRESS_DOMAIN_NAME:localhost:8080}
  imputation:
    # default workspace id is for this workspace in the dev environment
    # https://bvdp-saturn-dev.appspot.com/#workspaces/tsps_dev_bp_02_01_2024_v1/tsps_imputation_service_v1
    # this should be updated when trying to run on a bee.
    workspaceId: ${IMPUTATION_WORKSPACE_ID:b1d915cb-c1c8-40e4-bc85-8e7ba38f808e}
  kubernetes:
    in-kubernetes: ${TERRA_COMMON_KUBERNETES_IN_KUBERNETES:false}
    pod-name: ${TERRA_COMMON_KUBERNETES_POD_NAME:}
    pod-name-filter: ${TERRA_COMMON_KUBERNETES_POD_NAME_FILTER:}


# Below here is non-deployment-specific

# When the target is 'local' the write-config.sh script will generate this properties file. It
# contains the configuration of the TSPS test application. We can use that application in our
# integration testing to make sure the application code paths are working. However, we do not
# want it to appear in production environments.
# Imports are treated as additional documents inserted below this one, so the
# properties in local-properties are guaranteed to override values here in application.yml
spring.config.import: optional:file:../config/local-properties.yml, classpath:rendered/version.properties

logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: pipelines

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 8 # cpu count * 2 https://kwahome.medium.com/database-connections-less-is-more-86c406b6fad
    password: ${env.db.pipelines.pass}
    uri: ${env.db.host}/${env.db.pipelines.name}
    url: ${env.db.host}/${env.db.pipelines.name}
    username: ${env.db.pipelines.user}

  liquibase:
    change-log: '/db/changelog.xml'
    contexts: dev # This line currently does nothing but tell it NOT to pick up the test context, which holds test data

  stairway-database:
    password: ${env.db.stairway.pass}
    uri: ${env.db.host}/${env.db.stairway.name}
    username: ${env.db.stairway.user}

  main:
    allow-bean-definition-overriding: true

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
      static-locations: classpath:/static/

# Used to expose prometheus metrics using actuator
# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints
management:
  server:
    port: 9098
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      # Used to publish a histogram suitable for computing aggregates (across dimensions) percentile
      # latency approximations in Prometheus (by using histogram_quantile)
      # For more information: https://docs.micrometer.io/micrometer/reference/concepts/histogram-quantiles.html
      percentiles-histogram[http.server.requests]: true

imputation:
  workspaceId: ${env.imputation.workspaceId}
  cromwellSubmissionPollingIntervalInSeconds: 600 # poll every 10 minutes for a cromwell submission

pipelines:
  ingress:
    domainName: ${env.ingress.domainName}

  stairway-job:
    max-threads: 4
    polling-interval-seconds: 1
    resource-id: terra-scientific-pipelines-service
    timeout-seconds: 1800

  status-check:
    enabled: true
    pollingIntervalSeconds: 60
    startupWaitSeconds: 5
    stalenessThresholdSeconds: 125

  sentry:
    dsn: ${SENTRY_DSN:}
    environment: ${DEPLOY_ENV:}

terra.common:
  kubernetes:
    in-kubernetes: ${env.kubernetes.in-kubernetes} # whether to use a pubsub queue for Stairway; if false, use a local queue
    pod-name: ${env.kubernetes.pod-name}
    pod-name-filter: ${env.kubernetes.pod-name-filter}

  # these values are used by TCL
  stairway:
    cluster-name-suffix: tsps-stairway
    force-clean-start: false # ${env.db.init}
    max-parallel-flights: 50
    migrate-upgrade: true
    quiet-down-timeout: 30s
    terminate-timeout: 30s
    tracing-enabled: true
    retention-check-interval: 1d
    completed-flight-retention: 90d

  tracing:
    stackdriverExportEnabled: ${env.tracing.exportEnabled}
    samplingRate: ${env.tracing.samplingRate}

sam:
  baseUri: ${env.urls.sam}

leonardo:
  baseUri: ${env.urls.leonardo}
  # The below appTypeNames are in priority order for the named app type. This order is necessary for
  # the appComparisonFunction() located in AppUtils.java for selecting the best app for each app type.
  wdsAppTypeNames: ['WDS']
  cbasAppTypeNames: ['WORKFLOWS_APP', 'CROMWELL']
  dependencyUrlCacheTtlSeconds: 300 # Refresh every 5 minutes
  debugApiLogging: false

wds:
  apiV: "v0.2"
  debugApiLogging: false

cbas:
  debugApiLogging: false
