# This env section is for deployment-specific values
env:
  pipelines:
    arrayImputation:
      "1":
        # the default currently points to the GCP dev workspace teaspoons-imputation-dev/teaspoons_imputation_dev_storage_workspace_20240726
        storageWorkspaceContainerUrl: ${ARRAY_IMPUTATION_STORAGE_WORKSPACE_STORAGE_URL:gs://fc-secure-10efd4d7-392a-4e9e-89ea-d6629fbb06cc}
        referencePanelPathPrefixCustomValue: ${ARRAY_IMPUTATION_REFERENCE_PANEL_PATH_PREFIX_CUSTOM_VALUE_V1:/hg38/ref_panels/1000G_HGDP_no_singletons/hgdp.tgp.gwaspy.AN_added.bcf.ac2}
      "2":
        # the default currently points to the GCP dev workspace teaspoons-imputation-dev/teaspoons_imputation_dev_storage_workspace_20240726
        storageWorkspaceContainerUrl: ${ARRAY_IMPUTATION_STORAGE_WORKSPACE_STORAGE_URL:gs://fc-secure-10efd4d7-392a-4e9e-89ea-d6629fbb06cc}
        referencePanelPathPrefixCustomValue: ${ARRAY_IMPUTATION_REFERENCE_PANEL_PATH_PREFIX_CUSTOM_VALUE_V2:/hg38/ref_panels/1000G_HGDP_no_singletons/hgdp.tgp.gwaspy.AN_added.bcf.ac2}
    lowPassImputation:
      "1":
        # the default currently points to the GCP dev workspace teaspoons-lowpass-imputation-dev/teaspoons_low_pass_imputation_dev_storage_workspace_20260515
        storageWorkspaceContainerUrl: ${LOW_PASS_IMPUTATION_STORAGE_WORKSPACE_STORAGE_URL:gs://fc-secure-13abc91f-fc43-479e-8d3b-80cd4ab887b2}
        referencePanelPrefixCustomValue: ${LOW_PASS_IMPUTATION_REFERENCE_PANEL_PREFIX_CUSTOM_VALUE_V1:/hg38/ref_panels/1000G_HGDP_with_trio_information/auxiliary_files/}

configurations:
  common:
    userDataTtlDays: 14
    quotaConsumedPollingIntervalSeconds: 60
    quotaConsumedUseCallCaching: true
    inputQcPollingIntervalSeconds: 60
    inputQcUseCallCaching: true
    mainToolPollingIntervalSeconds: 600
    mainToolUseCallCaching: true
    mainToolDeleteIntermediateFiles: false
    monitoringScriptPath: "gs://warp-testing-public/cromwell_monitoring_script2.sh"
  pipelineQuotas:
    arrayImputation:
      defaultQuota: 2500
      minQuotaConsumed: 500
      maxQuotaConsumed: 10000
      quotaUnits: SAMPLES
    lowPassImputation:
      defaultQuota: 0
      minQuotaConsumed: 100
      maxQuotaConsumed: 5000
      quotaUnits: SAMPLES
  pipelines:
    arrayImputation:
      1:
        displayName: All of Us + AnVIL Array Imputation
        description: Phase and impute genotypes using Beagle 5.5 with the All of Us + AnVIL reference panel of 515,579 samples.
        pipelineType: imputation
        toolName: ImputationBeagle
        memoryRetryMultiplier: 2.0
        inputDefinitions:
          - name: multiSampleVcf
            wdlVariableName: multi_sample_vcf
            displayName: multi-sample VCF file
            description: A bgzipped, multi-sample VCF containing array data from one or more chromosomes to be imputed
            type: FILE
            isRequired: true
            userProvided: true
            fileSuffix: .vcf.gz
          - name: outputBasename
            wdlVariableName: output_basename
            displayName: output basename
            description: The prefix for all of the outputs' filenames. May only contain alphanumeric characters, dashes, and underscores
            type: STRING
            isRequired: true
            userProvided: true
          - name: contigs
            wdlVariableName: contigs
            type: STRING_ARRAY
            isRequired: true
            userProvided: false
            defaultValue: '["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chr20","chr21","chr22"]'
          - name: geneticMapsPath
            wdlVariableName: genetic_maps_path
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.arrayImputation.1.storageWorkspaceContainerUrl}/hg38/plink-genetic-maps/
          - name: refDict
            wdlVariableName: ref_dict
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.arrayImputation.1.storageWorkspaceContainerUrl}/hg38/ref_dict/Homo_sapiens_assembly38.dict
          - name: referencePanelPathPrefix
            wdlVariableName: reference_panel_path_prefix
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.arrayImputation.1.storageWorkspaceContainerUrl}${env.pipelines.arrayImputation.1.referencePanelPathPrefixCustomValue}
          - name: pipelineHeaderLine
            wdlVariableName: pipeline_header_line
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ScientificServicesPipeline=ArrayImputation_v1
          - name: minDr2ForInclusion
            wdlVariableName: min_dr2_for_inclusion
            displayName: minimum imputation quality for inclusion
            description: The minimum imputation quality (DR2) for inclusion in output VCF. Value must be between 0 and 1 (inclusive). Default is 0.0
            type: FLOAT
            isRequired: false
            userProvided: true
            defaultValue: "0.0"
            minValue: 0.0
            maxValue: 1.0
        outputDefinitions:
          - name: imputedMultiSampleVcf
            wdlVariableName: imputed_multi_sample_vcf
            displayName: imputed multi-sample VCF
            description: A multi-sample VCF file containing imputed genotypes for all samples
            type: FILE
            isRequired: true
          - name: imputedMultiSampleVcfIndex
            wdlVariableName: imputed_multi_sample_vcf_index
            displayName: imputed multi-sample VCF index
            description: An index file for the imputed multi-sample VCF file
            type: FILE
            isRequired: true
          - name: chunksInfo
            wdlVariableName: chunks_info
            displayName: imputation chunks QC TSV
            description: A TSV file containing QC information about the chunks used during imputation
            type: FILE
            isRequired: true
          - name: contigsInfo
            wdlVariableName: contigs_info
            displayName: contigs metrics TSV
            description: A TSV file containing metrics information about the input contigs (chromosomes)
            type: FILE
            isRequired: true
      2:
        displayName: All of Us + AnVIL Array Imputation
        description: Phase and impute genotypes using Beagle with the All of Us + AnVIL reference panel of 515,579 samples.
        pipelineType: imputation
        toolName: ImputationBeagle
        memoryRetryMultiplier: 2.0
        inputDefinitions:
          - name: multiSampleVcf
            wdlVariableName: multi_sample_vcf
            displayName: multi-sample VCF file
            description: A bgzipped, multi-sample VCF containing array data from one or more chromosomes to be imputed
            type: FILE
            isRequired: true
            userProvided: true
            fileSuffix: .vcf.gz
          - name: outputBasename
            wdlVariableName: output_basename
            displayName: output basename
            description: The prefix for all of the outputs' filenames. May only contain alphanumeric characters, dashes, and underscores
            type: STRING
            isRequired: true
            userProvided: true
          - name: minDr2ForInclusion
            wdlVariableName: min_dr2_for_inclusion
            displayName: minimum imputation quality for inclusion
            description: The minimum imputation quality (DR2) for inclusion in output VCF. Value must be between 0 and 1 (inclusive). Default is 0.0
            type: FLOAT
            isRequired: false
            userProvided: true
            defaultValue: "0.0"
            minValue: 0.0
            maxValue: 1.0
          - name: contigs
            wdlVariableName: contigs
            type: STRING_ARRAY
            isRequired: true
            userProvided: false
            defaultValue: '["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chr20","chr21","chr22"]'
          - name: geneticMapsPath
            wdlVariableName: genetic_maps_path
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.arrayImputation.2.storageWorkspaceContainerUrl}/hg38/plink-genetic-maps/
          - name: refDict
            wdlVariableName: ref_dict
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.arrayImputation.2.storageWorkspaceContainerUrl}/hg38/ref_dict/Homo_sapiens_assembly38.dict
          - name: referencePanelPathPrefix
            wdlVariableName: reference_panel_path_prefix
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.arrayImputation.2.storageWorkspaceContainerUrl}${env.pipelines.arrayImputation.2.referencePanelPathPrefixCustomValue}
          - name: pipelineHeaderLine
            wdlVariableName: pipeline_header_line
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ScientificServicesPipeline=ArrayImputation_v2
        outputDefinitions:
          - name: imputedMultiSampleVcf
            wdlVariableName: imputed_multi_sample_vcf
            displayName: imputed multi-sample VCF
            description: A multi-sample VCF file containing imputed variant genotypes for all samples
            type: FILE
            isRequired: true
          - name: imputedMultiSampleVcfIndex
            wdlVariableName: imputed_multi_sample_vcf_index
            displayName: imputed multi-sample VCF index
            description: An index file for the imputed multi-sample VCF file
            type: FILE
            isRequired: true
          - name: chunksInfo
            wdlVariableName: chunks_info
            displayName: imputation chunks QC TSV
            description: A TSV file containing QC information about the chunks used during imputation
            type: FILE
            isRequired: true
          - name: contigsInfo
            wdlVariableName: contigs_info
            displayName: contigs metrics TSV
            description: A TSV file containing metrics information about the input contigs (chromosomes)
            type: FILE
            isRequired: true
          - name: imputedHomRefSitesOnlyVcf
            wdlVariableName: imputed_hom_ref_sites_only_vcf
            displayName: imputed hom ref sites only VCF
            description: A sites only VCF file containing information about homozygous reference sites
            type: FILE
            isRequired: true
          - name: imputedHomRefSitesOnlyVcfIndex
            wdlVariableName: imputed_hom_ref_sites_only_vcf_index
            displayName: imputed hom ref sites only VCF index
            description: An index file for the imputed homozygous reference sites only VCF file
            type: FILE
            isRequired: true
    lowPassImputation:
      1:
        displayName: All of Us + AnVIL Low Pass WGS Imputation
        description: Phase and impute low pass WGS or BGE data using GLIMPSE2 with the All of Us + AnVIL reference panel of 515,579 samples.
        pipelineType: imputation
        toolName: Glimpse2LowPassImputation
        memoryRetryMultiplier: 1.5
        inputDefinitions:
          - name: cramManifest
            wdlVariableName: cram_manifest
            displayName: CRAM manifest TSV file
            description: Manifest TSV file containing columns (including header line) of sample_id, cram_path, and cram_index_path referring to cloud-hosted input files to be imputed
            type: MANIFEST
            isRequired: true
            userProvided: true
            fileSuffix: .tsv
          - name: outputBasename
            wdlVariableName: output_basename
            displayName: output basename
            description: The prefix for all of the outputs' filenames. May only contain alphanumeric characters, dashes, and underscores
            type: STRING
            isRequired: true
            userProvided: true
          - name: infoFilterForInclusion
            wdlVariableName: info_filter_for_inclusion
            displayName: minimum imputation quality for inclusion
            description: The minimum imputation quality for inclusion in output VCF. Value must be between 0 and 1 (inclusive). Default is 0.0
            type: FLOAT
            isRequired: false
            userProvided: true
            defaultValue: "0.0"
            minValue: 0.0
            maxValue: 1.0
          - name: contigs
            wdlVariableName: contigs
            type: STRING_ARRAY
            isRequired: true
            userProvided: false
            defaultValue: '["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chr20","chr21","chr22"]'
          - name: referencePanelPrefix
            wdlVariableName: reference_panel_prefix
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.lowPassImputation.1.storageWorkspaceContainerUrl}${env.pipelines.lowPassImputation.1.referencePanelPrefixCustomValue}
          - name: fasta
            wdlVariableName: fasta
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.lowPassImputation.1.storageWorkspaceContainerUrl}/hg38/ref_files/Homo_sapiens_assembly38.fasta
          - name: fastaIndex
            wdlVariableName: fasta_index
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.lowPassImputation.1.storageWorkspaceContainerUrl}/hg38/ref_files/Homo_sapiens_assembly38.fasta.fai
          - name: refDict
            wdlVariableName: ref_dict
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ${env.pipelines.lowPassImputation.1.storageWorkspaceContainerUrl}/hg38/ref_files/Homo_sapiens_assembly38.dict
          - name: pipelineHeaderLine
            wdlVariableName: pipeline_header_line
            type: STRING
            isRequired: true
            userProvided: false
            defaultValue: ScientificServicesPipeline=LowPassImputation_v1
        outputDefinitions:
          - name: imputedVcf
            wdlVariableName: imputed_vcf
            displayName: imputed multi-sample VCF
            description: A multi-sample VCF file containing imputed variant genotypes for all samples
            type: FILE
            isRequired: true
          - name: imputedVcfIndex
            wdlVariableName: imputed_vcf_index
            displayName: imputed multi-sample VCF index
            description: An index file for the imputed multi-sample VCF file
            type: FILE
            isRequired: true
          - name: imputedHomRefSitesOnlyVcf
            wdlVariableName: imputed_hom_ref_sites_only_vcf
            displayName: imputed hom ref sites only VCF
            description: A sites only VCF file containing information about homozygous reference sites
            type: FILE
            isRequired: true
          - name: imputedHomRefSitesOnlyVcfIndex
            wdlVariableName: imputed_hom_ref_sites_only_vcf_index
            displayName: imputed hom ref sites only VCF index
            description: An index file for the imputed homozygous reference sites only VCF file
            type: FILE
            isRequired: true
          - name: qcMetrics
            wdlVariableName: qc_metrics
            displayName: QC metrics TSV file
            description: A TSV file containing metrics about the imputed output data
            type: FILE
            isRequired: true
